<?php
	$title = 'Delete user';
	$this->headTitle($title);
?>
	<h1><?php echo $this->escape($title); ?></h1>
	<p>Are you sure that you want to delete
		'<?php echo $this->escape($user['firstname']); ?>' ,
		'<?php echo $this->escape($user['lastname']); ?>',
		'<?php echo $this->escape($user['password']); ?>'?
	</p>
	<?php
		$url = $this->url('default',
		array('controller' => 'user', 'action' => 'delete')); ?>
		<form action="<?php echo $url; ?>" method="post">
			<div>
			<input type="hidden" name="id" value="<?php echo (int)$user['id']; ?>" />
			<input type="submit" name="del" value="Yes" />
			<input type="submit" name="del" value="No" />
			</div>
		</form>