<?php
	$title = 'My users';
	$this->headTitle($title);
	?>
	<h1><?php echo $this->escape($title); ?></h1>
	<p><a href="<?php echo $this->url('default', array('controller'=>'user',
	'action'=>'add'));?>">Add new user</a></p>
	
	<p><a href="<?php echo $this->url('default', array('controller'=>'user',
	'action'=>'login'));?>">Logout</a></p>
	<table class="table">
		<tr>
			<th>First Name</th>
			<th>Last Name</th>
			<th>&nbsp;</th>
		</tr>
		<?php foreach($this->users as $myuser) : ?>
			<tr>				
				<td><?php echo $this->escape($myuser->firstname); /* it used to be:  $myuser["firstname"] and $myuser->$firstname*/ ?></td> 
				<td><?php echo $this->escape($myuser->lastname);?></td>
				<td>
					<a href="<?php echo $this->url('default',
					array('controller'=>'user','action'=>'edit'))
					. '?id=' . $myuser->id ;?>">Edit</a>
					<a href="<?php echo $this->url('default',
					array('controller'=>'user','action'=>'delete'))
					. '?id=' . $myuser->id ;?>">Delete</a>
				</td>
			</tr>
		<?php endforeach; ?>		
	</table>